version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
